SECRET_KEY = ''
DBMySQL_HOST = ''
DBMySQL_USER = ''
DBMySQL_PASS = ''
DBMySQL_NAME = ''
DBMySQL_PORT = 0000
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://'+DBMySQL_USER+':'+DBMySQL_PASS+'@'+DBMySQL_HOST+'/'+DBMySQL_NAME+'?charset=utf8&use_unicode=0'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SHOW_SQLALCHEMY_LOG_MESSAGES = False

ERROR_404_HELP = False