SECRET_KEY = ''
DBMySQL_HOST = ''
DBMySQL_USER = ''
DBMySQL_PASS = ''
DBMySQL_NAME = ''
DBMySQL_PORT = 5432
SQLALCHEMY_DATABASE_URI = 'postgresql+psycopg2://'+DBMySQL_USER+':'+DBMySQL_PASS+'@'+DBMySQL_HOST+'/'+DBMySQL_NAME
SQLALCHEMY_TRACK_MODIFICATIONS = False
SHOW_SQLALCHEMY_LOG_MESSAGES = False
JWT_SECRET_KEY = ''

ERROR_404_HELP = False